/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as SkillsRouteImport } from './routes/skills'
import { Route as STurnIdRouteRouteImport } from './routes/s/$turnId/route'
import { Route as STurnIdPEmpIdRouteImport } from './routes/s/$turnId/p.$empId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const SkillsRoute = SkillsRouteImport.update({
  id: '/skills',
  path: '/skills',
  getParentRoute: () => rootRouteImport,
} as any)
const STurnIdRouteRoute = STurnIdRouteRouteImport.update({
  id: '/s/$turnId',
  path: '/s/$turnId',
  getParentRoute: () => rootRouteImport,
} as any)
const STurnIdPEmpIdRoute = STurnIdPEmpIdRouteImport.update({
  id: '/p/$empId',
  path: '/p/$empId',
  getParentRoute: () => STurnIdRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/skills': typeof SkillsRoute
  '/s/$turnId': typeof STurnIdRouteRouteWithChildren
  '/s/$turnId/p/$empId': typeof STurnIdPEmpIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/skills': typeof SkillsRoute
  '/s/$turnId': typeof STurnIdRouteRouteWithChildren
  '/s/$turnId/p/$empId': typeof STurnIdPEmpIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/skills': typeof SkillsRoute
  '/s/$turnId': typeof STurnIdRouteRouteWithChildren
  '/s/$turnId/p/$empId': typeof STurnIdPEmpIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/skills' | '/s/$turnId' | '/s/$turnId/p/$empId'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/skills' | '/s/$turnId' | '/s/$turnId/p/$empId'
  id: '__root__' | '/' | '/skills' | '/s/$turnId' | '/s/$turnId/p/$empId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  SkillsRoute: typeof SkillsRoute
  STurnIdRouteRoute: typeof STurnIdRouteRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/skills': {
      id: '/skills'
      path: '/skills'
      fullPath: '/skills'
      preLoaderRoute: typeof SkillsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/s/$turnId': {
      id: '/s/$turnId'
      path: '/s/$turnId'
      fullPath: '/s/$turnId'
      preLoaderRoute: typeof STurnIdRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/s/$turnId/p/$empId': {
      id: '/s/$turnId/p/$empId'
      path: '/p/$empId'
      fullPath: '/s/$turnId/p/$empId'
      preLoaderRoute: typeof STurnIdPEmpIdRouteImport
      parentRoute: typeof STurnIdRouteRoute
    }
  }
}

interface STurnIdRouteRouteChildren {
  STurnIdPEmpIdRoute: typeof STurnIdPEmpIdRoute
}

const STurnIdRouteRouteChildren: STurnIdRouteRouteChildren = {
  STurnIdPEmpIdRoute: STurnIdPEmpIdRoute,
}

const STurnIdRouteRouteWithChildren = STurnIdRouteRoute._addFileChildren(
  STurnIdRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  SkillsRoute: SkillsRoute,
  STurnIdRouteRoute: STurnIdRouteRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
