/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as DataRouteImport } from './routes/data'
import { Route as SkillsRouteImport } from './routes/skills'
import { Route as TasksRouteImport } from './routes/tasks'
import { Route as ApiReviewRouteImport } from './routes/api/review'
import { Route as DataEmpIdRouteImport } from './routes/data.$empId'
import { Route as STurnIdRouteRouteImport } from './routes/s/$turnId/route'
import { Route as SkillsWordRouteImport } from './routes/skills.$word'
import { Route as STurnIdPEmpIdRouteImport } from './routes/s/$turnId/p.$empId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DataRoute = DataRouteImport.update({
  id: '/data',
  path: '/data',
  getParentRoute: () => rootRouteImport,
} as any)
const SkillsRoute = SkillsRouteImport.update({
  id: '/skills',
  path: '/skills',
  getParentRoute: () => rootRouteImport,
} as any)
const TasksRoute = TasksRouteImport.update({
  id: '/tasks',
  path: '/tasks',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiReviewRoute = ApiReviewRouteImport.update({
  id: '/api/review',
  path: '/api/review',
  getParentRoute: () => rootRouteImport,
} as any)
const DataEmpIdRoute = DataEmpIdRouteImport.update({
  id: '/$empId',
  path: '/$empId',
  getParentRoute: () => DataRoute,
} as any)
const STurnIdRouteRoute = STurnIdRouteRouteImport.update({
  id: '/s/$turnId',
  path: '/s/$turnId',
  getParentRoute: () => rootRouteImport,
} as any)
const SkillsWordRoute = SkillsWordRouteImport.update({
  id: '/$word',
  path: '/$word',
  getParentRoute: () => SkillsRoute,
} as any)
const STurnIdPEmpIdRoute = STurnIdPEmpIdRouteImport.update({
  id: '/p/$empId',
  path: '/p/$empId',
  getParentRoute: () => STurnIdRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/data': typeof DataRouteWithChildren
  '/skills': typeof SkillsRouteWithChildren
  '/tasks': typeof TasksRoute
  '/s/$turnId': typeof STurnIdRouteRouteWithChildren
  '/api/review': typeof ApiReviewRoute
  '/data/$empId': typeof DataEmpIdRoute
  '/skills/$word': typeof SkillsWordRoute
  '/s/$turnId/p/$empId': typeof STurnIdPEmpIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/data': typeof DataRouteWithChildren
  '/skills': typeof SkillsRouteWithChildren
  '/tasks': typeof TasksRoute
  '/s/$turnId': typeof STurnIdRouteRouteWithChildren
  '/api/review': typeof ApiReviewRoute
  '/data/$empId': typeof DataEmpIdRoute
  '/skills/$word': typeof SkillsWordRoute
  '/s/$turnId/p/$empId': typeof STurnIdPEmpIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/data': typeof DataRouteWithChildren
  '/skills': typeof SkillsRouteWithChildren
  '/tasks': typeof TasksRoute
  '/s/$turnId': typeof STurnIdRouteRouteWithChildren
  '/api/review': typeof ApiReviewRoute
  '/data/$empId': typeof DataEmpIdRoute
  '/skills/$word': typeof SkillsWordRoute
  '/s/$turnId/p/$empId': typeof STurnIdPEmpIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/data'
    | '/skills'
    | '/tasks'
    | '/s/$turnId'
    | '/api/review'
    | '/data/$empId'
    | '/skills/$word'
    | '/s/$turnId/p/$empId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/data'
    | '/skills'
    | '/tasks'
    | '/s/$turnId'
    | '/api/review'
    | '/data/$empId'
    | '/skills/$word'
    | '/s/$turnId/p/$empId'
  id:
    | '__root__'
    | '/'
    | '/data'
    | '/skills'
    | '/tasks'
    | '/s/$turnId'
    | '/api/review'
    | '/data/$empId'
    | '/skills/$word'
    | '/s/$turnId/p/$empId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DataRoute: typeof DataRouteWithChildren
  SkillsRoute: typeof SkillsRouteWithChildren
  TasksRoute: typeof TasksRoute
  STurnIdRouteRoute: typeof STurnIdRouteRouteWithChildren
  ApiReviewRoute: typeof ApiReviewRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/data': {
      id: '/data'
      path: '/data'
      fullPath: '/data'
      preLoaderRoute: typeof DataRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/skills': {
      id: '/skills'
      path: '/skills'
      fullPath: '/skills'
      preLoaderRoute: typeof SkillsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tasks': {
      id: '/tasks'
      path: '/tasks'
      fullPath: '/tasks'
      preLoaderRoute: typeof TasksRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/review': {
      id: '/api/review'
      path: '/api/review'
      fullPath: '/api/review'
      preLoaderRoute: typeof ApiReviewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/data/$empId': {
      id: '/data/$empId'
      path: '/$empId'
      fullPath: '/data/$empId'
      preLoaderRoute: typeof DataEmpIdRouteImport
      parentRoute: typeof DataRoute
    }
    '/s/$turnId': {
      id: '/s/$turnId'
      path: '/s/$turnId'
      fullPath: '/s/$turnId'
      preLoaderRoute: typeof STurnIdRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/skills/$word': {
      id: '/skills/$word'
      path: '/$word'
      fullPath: '/skills/$word'
      preLoaderRoute: typeof SkillsWordRouteImport
      parentRoute: typeof SkillsRoute
    }
    '/s/$turnId/p/$empId': {
      id: '/s/$turnId/p/$empId'
      path: '/p/$empId'
      fullPath: '/s/$turnId/p/$empId'
      preLoaderRoute: typeof STurnIdPEmpIdRouteImport
      parentRoute: typeof STurnIdRouteRoute
    }
  }
}

interface DataRouteChildren {
  DataEmpIdRoute: typeof DataEmpIdRoute
}

const DataRouteChildren: DataRouteChildren = {
  DataEmpIdRoute: DataEmpIdRoute,
}

const DataRouteWithChildren = DataRoute._addFileChildren(DataRouteChildren)

interface SkillsRouteChildren {
  SkillsWordRoute: typeof SkillsWordRoute
}

const SkillsRouteChildren: SkillsRouteChildren = {
  SkillsWordRoute: SkillsWordRoute,
}

const SkillsRouteWithChildren =
  SkillsRoute._addFileChildren(SkillsRouteChildren)

interface STurnIdRouteRouteChildren {
  STurnIdPEmpIdRoute: typeof STurnIdPEmpIdRoute
}

const STurnIdRouteRouteChildren: STurnIdRouteRouteChildren = {
  STurnIdPEmpIdRoute: STurnIdPEmpIdRoute,
}

const STurnIdRouteRouteWithChildren = STurnIdRouteRoute._addFileChildren(
  STurnIdRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DataRoute: DataRouteWithChildren,
  SkillsRoute: SkillsRouteWithChildren,
  TasksRoute: TasksRoute,
  STurnIdRouteRoute: STurnIdRouteRouteWithChildren,
  ApiReviewRoute: ApiReviewRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
